# Generated by Django 2.1.5 on 2021-04-06 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_customer'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='repassword',
            field=models.CharField(default='', max_length=500),
        ),
    ]
